rules:
  - test: '.*ts'
    watch_dir: C:\Users\zanllp\Downloads\Video
    emit: move_to_saved_dir
  - test: '.*'
    watch_dir: 'F:\BaiduNetdiskDownload'
    priority: -1
    emit: try_unpack
  - test: '\d+_p0_master1200.jpg'
    watch_dir: C:\Users\zanllp\Desktop
    execute: !Copy
      target: E:\_归档\pixiv_img
tasks:
  try_unpack: !TryUnpack
    pwd: 111111
  move_to_saved_dir: !Move
    target: 'E:\_归档\!3'
debounce_time: 300